/* Check the browser solver against the Python one.
 *
 * The browser runs a coarser lattice than aero/analyse.py on purpose, so the
 * two will not agree exactly. What has to hold is that they describe the same
 * car: the same downforce to within a stated tolerance, the same sign, and the
 * same response to ground effect.
 */
import { Tunnel } from '../viewer/windtunnel.js';
import { readFileSync } from 'node:fs';

/* The config comes from viewer/parts.json, which is what the page loads.
 *
 * It used to come from a second copy in tools/tunnel.json, generated by hand
 * and committed -- and that copy was stale. The front wing's elements were
 * respaced in spec.py from 34/76/124 mm to 64/106/168 and this file went on
 * solving the old stack, where element 1 sat ten millimetres under element 0.
 * Two lifting surfaces that close give a near-singular influence matrix: the
 * solve answered with +2015 and -3198 of circulation on two elements of the
 * same wing, which nearly cancel in the force and do not cancel at all in the
 * induced drag. There is one config now, and it is the one the viewer runs. */
const manifest = JSON.parse(
  readFileSync(new URL('../viewer/parts.json', import.meta.url)));
const cfg = manifest.tunnel;
const ctl = {}; for(const c of cfg.controls) ctl[c.id] = c.value;

const t = new Tunnel(cfg);
const v = cfg.v_default;
const q = 0.5*1.225*v*v;

console.log('\nBROWSER SOLVER CHECK  (VX-1 wings, in ground effect)');
console.log(`  reference area ${cfg.s_ref.toFixed(3)} m2   speed ${(v*3.6).toFixed(0)} km/h`);

let a = performance.now();
const ge = t.solve({alpha: 0, v, controls: ctl, ground: true});
const t1 = performance.now() - a;
const free = t.solve({alpha: 0, v, controls: ctl, ground: false});
a = performance.now();
for(let i = 0; i < 30; i++) t.solve({alpha: 0, v, controls: {...ctl, drs: i}, ground: true});
const per = (performance.now() - a)/30;

const dfGE = -ge.CL*q*cfg.s_ref/9.81;
const dfFree = -free.CL*q*cfg.s_ref/9.81;

console.log(`\n  panels ${ge.panels}   first solve ${t1.toFixed(0)} ms`
          + `   repeat ${per.toFixed(2)} ms`);
console.log(`  free air        ${dfFree.toFixed(0)} kg`);
console.log(`  in ground effect${dfGE.toFixed(0).padStart(9)} kg`
          + `   (${((dfGE/dfFree-1)*100).toFixed(1)} %)`);
console.log(`  induced drag    ${(ge.CDi*q*cfg.s_ref/9.81).toFixed(0)} kg-force`);
console.log(`  downforce/drag  ${ge.LD.toFixed(1)}`);

console.log('\n  DRS sweep (rear flap opening sheds downforce and drag):');
for(const d of [0, 8, 16, 24, 28]){
  const s = t.solve({alpha: 0, v, controls: {...ctl, drs: d}, ground: true});
  console.log(`    ${String(d).padStart(2)} deg   downforce ${(-s.CL*q*cfg.s_ref/9.81).toFixed(0).padStart(4)} kg`
            + `   drag ${(s.CDi*q*cfg.s_ref/9.81).toFixed(0).padStart(4)} kg`);
}

console.log('\n  Front flap sweep (aero balance):');
for(const d of [-6, -3, 0, 5, 10]){
  const s = t.solve({alpha: 0, v, controls: {...ctl, front_flap: d}, ground: true});
  let f = 0, tot = 0;
  for(const [k, val] of Object.entries(s.bySurface)){
    tot += val; if(cfg.front_surfaces.includes(k)) f += val;
  }
  console.log(`    ${String(d).padStart(3)} deg   downforce ${(-s.CL*q*cfg.s_ref/9.81).toFixed(0).padStart(4)} kg`
            + `   front share ${(f/tot*100).toFixed(0)} %`);
}

/* Is the answer converged, and is the loading smooth?
 *
 * Agreeing with Python is necessary and nowhere near sufficient: both solvers
 * read the same spec.py, so a lattice that cannot resolve the car agrees with
 * itself. Two checks that catch what that one cannot:
 *
 *   - refine chordwise and see whether the answer moves. It used not to
 *     converge at all -- doubling the chordwise panels took the induced drag
 *     from 3.0 to 24 to 214 -- because the rear wing's two elements
 *     interpenetrated and because the vortex core was smothering each panel's
 *     own bound vortex.
 *   - check the spanwise loading for alternating sign, which is what a
 *     near-singular influence matrix produces. Lift nearly cancels across
 *     such a pair; induced drag, being quadratic, does not cancel at all.
 */
console.log('\n  Chordwise convergence:');
const conv = [];
for(const nc of [2, 3, 6, 12]){
  const c2 = JSON.parse(JSON.stringify(cfg));
  for(const s of c2.surfaces) s.n_chord = nc;
  const r = new Tunnel(c2).solve({alpha: 0, v, controls: ctl, ground: true});
  conv.push({nc, df: -r.CL*q*cfg.s_ref/9.81, dr: r.CDi*q*cfg.s_ref/9.81,
             rough: r.roughness, ring: r.ringing, surf: r.ringingSurface});
  const last = conv[conv.length-1];
  console.log(`    ${String(nc).padStart(2)} per chord  downforce ${last.df.toFixed(0).padStart(4)} kg`
            + `   drag ${last.dr.toFixed(0).padStart(4)} kg`
            + `   loading roughness ${last.rough.toFixed(2)}`
            + (last.ring ? `  RINGING on ${last.surf}` : ''));
}
const dfs = conv.map(c => c.df), drs2 = conv.map(c => c.dr);
const spreadL = (Math.max(...dfs)/Math.min(...dfs) - 1)*100;
const spreadD = (Math.max(...drs2)/Math.min(...drs2) - 1)*100;
const rings = conv.filter(c => c.ring);

// Python reports this in ground effect at 250 km/h on a finer lattice.
const REF = 789;
const err = Math.abs(dfGE/REF - 1)*100;
const okRef = err < 15 && dfGE > 0 && dfGE > dfFree;
const okConv = spreadL < 5 && spreadD < 8;
const okRing = rings.length === 0;
const ok = okRef && okConv && okRing;

console.log('\n' + '='.repeat(62));
console.log(`  against aero/analyse.py: ${dfGE.toFixed(0)} kg vs ${REF} kg`
          + `  (${err.toFixed(0)} %, limit 15 %)`);
console.log(`  chordwise 2 -> 12 panels: downforce spreads ${spreadL.toFixed(1)} %`
          + ` (limit 5), drag ${spreadD.toFixed(1)} % (limit 8)`);
console.log(`  spanwise loading smooth at every refinement: `
          + (okRing ? 'yes' : `NO -- ${rings.map(r => r.surf).join(', ')}`));
console.log(ok ? 'PASS  browser solver agrees with Python and is converged'
               : 'FAIL  ' + [!okRef && 'disagrees with Python',
                             !okConv && 'not converged',
                             !okRing && 'lattice is ringing']
                            .filter(Boolean).join('; '));
process.exit(ok ? 0 : 1);
